### ISSUE TITLE
movement-controls broken with aframe 1.2.0

### ISSUE THREAD

**Issue by Turtleted21** [c-frame/aframe-extras#349]
Hi 
movement-controls broken with aframe 1.2.0
` <a-entity id="player" movement-controls="constrainToNavMesh: true; controls: keyboard" position="0 0 60" rotation="0 0 0">`
worked with aframe 1.1.0

Thanks

**Comment by n5ro** [comment]
The big breaking change with threejs this month was the depreciation of Geometry, and the requirement that we use BufferGeometry instead. I found only one instance of THREE.Geometry in Aframe Extras and I merged a PR to fix it to THREE.BufferGeometry. This affected navmesh specifically. Try your code again and let me know if this fixed it or not.

**Comment by jaydhulia** [comment]
Hi @n5ro , I was wondering how do we test whether it works with the latest code changes or not? I tried to use https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@geometry/dist/aframe-extras.min.js as the src, but it still had THREE.Geometry. Is it possible to elaborate on how to use the latest changes to test it?
Thanks!

**Comment by jaydhulia** [comment]
Edit: It also seems that the PR won't fix it, because https://github.com/n5ro/aframe-extras/blob/afcebe83edfe9bcbda0dcf055ff399f34d8f2a5f/src/pathfinding/system.js#L20 this function still expects a three.geometry object as a parameter?

**Comment by rossbishop** [comment]
Still having issues with Navmesh because of this. Results in "THREE.Geometry is not a constructor" error.

https://github.com/n5ro/aframe-extras/blob/afcebe83edfe9bcbda0dcf055ff399f34d8f2a5f/dist/aframe-extras.js#L11127

I can see the change you made in the PR @n5ro, that might fix it, I'll have to build it locally. Would make sense for the dist to be rebuilt in the repo to reflect the new changes.

EDIT:

Okay, I see that that change isn't actually in the master branch anymore, perhaps because it doesn't work...? Using that change I get the error "(intermediate value).fromBufferGeometry is not a function"

**Comment by n5ro** [comment]
Yes I know about the issue with navmesh. I have been working on it, asking
questions, researching the problem, I have some ideas about what I need to
do to fix it.

Someone created a basic navmesh demo and I am using it to test a possible
fix

here is what I am working on now https://glitch.com/edit/#!/navmesh1

and here is an older version of it https://glitch.com/edit/#!/navmesh

Please feel free to remix these and use them to test possible solutions.


-- 
Sincerely,


Micah Blumberg
3+ years webxr code experience, 5+ years virtual reality & technology
journalist, he/him

Silicon Valley Global News (Science & Technology Journalism)
and VRMA.io Virtual Reality Magazine (WebXR based news),
http://svgn.io

Github
github.com/n5ro
github.com/micah1
<http://github.com/n5ro>

The Aframe WebXR Online Hacknight & San Francisco Virtual Reality
https://www.meetup.com/virtualreality/events

Auto-bio: http://vrma.io
Twitter: https://twitter.com/worksalt
instagram: https://www.instagram.com/micahsun/
linkedin: https://www.linkedin.com/in/worksalt/

**Comment by n5ro** [comment]
I'm still working on a fix to navmesh https://glitch.com/edit/#!/navmesh1
https://glitch.com/edit/#!/navmesh
https://glitch.com/edit/#!/navmesh2

Feel free to read the commented code in each index file for details. I am trying to replace Three.Geometry which has been deleted from threejs with BufferGeometry. I could use some help testing this and withing this code, please remix the links and try to get it working also. In the meantime use Aframe 1.1.0 with A-Frame Extras until we get this fixed.

**Comment by rossbishop** [comment]
Okay, I've got what I believe to be a fix for this.

See https://github.com/n5ro/aframe-extras/pull/358

**Comment by donmccurdy** [comment]
It might be worth bumping to `three-pathfinding` v0.14.1, it has some fixes for the Geometry/BufferGeometry situation that were not in v0.14.0. See https://github.com/donmccurdy/three-pathfinding/pull/77.

**Comment by vincentfretin** [comment]
I updated three-pathfinding to 1.1.0 in #388
